site_name: Zelfrijdend Hok
site_url: https://www.jouwprojectwebsite.com
site_description: Projectdocumentatie voor het Zelfrijdend Hok door Casper, Tjitte, Jeffrey & Jayden
site_author: Casper Oudman 2025

# Thema-instellingen
theme:
  name: material
  language: nl
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    primary: teal
    accent: lime
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs
    - header.autohide

# Markdown-extensies
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Extra CSS en JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright:
    &copy; 2025 | Gemaakt door het team met ğŸ’¡, ğŸš€ en een beetje koffie.  
    <br>  
    <span style="font-size: 12px;">ğŸ” Geheim tip: Klik op de punt aan het einde van deze regel...</span>  
    <span style="display: none;">ğŸ‰ Je hebt de verborgen boodschap gevonden! ğŸš€</span>
